name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger the action when pushing to the main branch
  pull_request:
    branches:
      - main   # Trigger for PRs targeting main branch

jobs:
  # Job to run the tests
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner (you can choose other OS options)
    
    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step 2: Set up Python (for a Python project)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.1'  # Change to your version of Python

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest tests/test_app.py  # Run the test suite

 